# Generated by Django 6.0.6 on 2026-06-08 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Part",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("order", models.FloatField(default=0)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("notebook", "Jupyter Notebook"),
                            ("markdown", "Markdown"),
                        ],
                        default="notebook",
                        max_length=20,
                    ),
                ),
                ("source_path", models.CharField(blank=True, max_length=500)),
                ("notebook_filename", models.CharField(blank=True, max_length=300)),
                ("html_content", models.TextField(blank=True)),
                ("is_intro", models.BooleanField(default=False)),
                (
                    "part",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="chapters",
                        to="webapp.part",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
